name: spanner
description: Router implementation for pharaoh, internally uses a Radix Tree (aka compact Prefix Tree), supports route params, wildcards.
version: 1.0.0
repository: https://github.com/Pharaoh-Framework/pharaoh/tree/main/packages/spanner

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  meta: ^1.11.0
  pharaoh: ^0.0.5

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  spookie: ^1.0.1
