name: pharaoh_static
description: Pharaoh Middleware that serves static files such as images, CSS files, and JavaScript files.
version: 1.0.1
repository: https://github.com/Pharaoh-Framework/pharaoh/tree/main/packages/pharaoh_static

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  convert: ^3.1.1
  http_parser: ^4.0.2
  mime: ^1.0.4
  path: ^1.8.3
  pharaoh: ^0.0.5

dev_dependencies:
  spookie: ^1.0.1
