name: spookie
description: SuperAgent driven library for testing Dart HTTP servers.
version: 1.0.1
repository: https://github.com/codekeyz/pharaoh/tree/main/packages/spookie

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.0.0
  test: ^1.24.9

dev_dependencies:
  pharaoh: ^0.0.5
