name: pharaoh_hotreload
description: Hot reloader for Pharaoh. Reloads your application whenever a file system change is detected in the source files or registered files.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

dependencies:
  glob: ^2.1.2
  vm_service: ^13.0.0
  watcher: ^1.1.0
  pharaoh:
  charcode: ^1.3.1
  path: ^1.8.3
  stream_transform: ^2.1.0
  collection: ^1.18.0
  logging: ^1.2.0
  hotreloader: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
